CREATE TABLE candidate_time_slots (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  candidate_id INT REFERENCES candidates(id) ON DELETE CASCADE,
  time_slot_id INT REFERENCES time_slots(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE UNIQUE INDEX candidate_time_slots_unique_idx
  ON candidate_time_slots
  USING btree (candidate_id, time_slot_id);

CREATE TRIGGER update_candidate_time_slots_updated_at
  BEFORE UPDATE ON candidate_time_slots
  FOR EACH ROW EXECUTE PROCEDURE modify_updated_at_column();
