CREATE TABLE candidate_time_slots (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  candidate_id INT REFERENCES candidates(id) ON DELETE CASCADE,
  time_slot_id INT REFERENCES time_slots(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX candidate_time_slots_unique_idx
  ON candidate_time_slots
  USING btree (candidate_id, time_slot_id);
