CREATE TABLE interviewers (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  email VARCHAR(255),
  created_at TIMESTAMP DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE TRIGGER update_interviewers_updated_at
  BEFORE UPDATE ON interviewers
  FOR EACH ROW EXECUTE PROCEDURE modify_updated_at_column();
