CREATE TABLE interviewer_time_slots (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  interviewer_id INT REFERENCES interviewers(id) ON DELETE CASCADE,
  time_slot_id INT REFERENCES time_slots(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE UNIQUE INDEX interviewer_time_slots_unique_idx
  ON interviewer_time_slots
  USING btree (interviewer_id, time_slot_id);

CREATE TRIGGER update_interviewer_time_slots_updated_at
  BEFORE UPDATE ON interviewer_time_slots
  FOR EACH ROW EXECUTE PROCEDURE modify_updated_at_column();
