CREATE TABLE interviewer_time_slots (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  interviewer_id INT REFERENCES interviewers(id) ON DELETE CASCADE,
  time_slot_id INT REFERENCES time_slots(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX interviewer_time_slots_unique_idx
  ON interviewer_time_slots
  USING btree (interviewer_id, time_slot_id);
