swagger: '2.0'
info:
  $ref: ./info.yaml
host: "candidatestore.swagger.io"
basePath: "/api"
schemes:
  - http
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
